project:
  type: book
  output-dir: docs

book:
  title: "Reddit Analysis"
  author: "Tim Ransom"
  date: "2/14/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - 10-source-data.qmd
    - 20-sentiment-analysis.qmd
    - 30-topic-modeling.qmd
    - 40-quant-ethnography.qmd

bibliography: references.bib

format:
  html:
    # code-tools:
    #   source: false
    #   toggle: true
    theme: cosmo
    code-block-background: true
    code-fold: true

editor: source

execute:
  cache: true
  freeze: auto  # re-render only when source changes

