# Preface {.unnumbered}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reddit

Reddit is a highly used pseudo-anonymous social media website.

I've pulled archives of Reddit posts and comments from pushshift, about one terabyte of compressed comment and post data. That's quite a bit of data to be sorting through!

## Spark

Reading through the Reddit data is a bit of a problem because of the size of the data. I'm using Apache spark to efficiently filter the data. The R interface to spark I'm using is sparklyr, which also includes machine learning capabilities.

## Sentiment Analysis

Sentiment analyses are the bread and butter of finding out the general vibe of an online space. Obviously there are many ways to describe the sentiments of the communities we're going to be analyzing but this gives us a good way to get off the ground.

## Topic Modeling

The actual things discussed in a subreddit (community of practice) can vary pretty wildly from what just the name of the subreddit would imply. For spaces related to programming or education, having a list of these gives us an idea of what broad communites think is needed to discuss to learn programming.

## Quantitative Ethnography

This is probably the most exciting method of the bunch. Quantitative ethnographies use an epistemic network analysis to address the underlying values of a group through the help of a semi automated qualitative coding process.



